<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Win32Resource>Resources.res</Win32Resource>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="App.config;packages.config;Application.xaml" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="MidPointConverter.fs" />
    <Compile Include="ExtendedScrollViewer.fs" />
    <Compile Include="SmokeTest.fs" />
    <Compile Include="App.fs" />
    <Resource Include="MainWindow.xaml" />
    <Resource Include="TimeLine.xaml" />
    <Resource Include="Icon.xaml" />
    <Resource Include="resources\restart.ico" />
    <Resource Include="resources\quit.ico" />
    <Resource Include="TimesUpTimer.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WpfScreenHelper" Version="2.1.1" />
  </ItemGroup>
</Project>